### ISSUE TITLE
SQD-8 Реализовать класс UserInRole и добавить соответствующий файл маппинга

### ISSUE THREAD

**Issue by kartman3103** [MechTeam/MechProject#14]
В папке Domain.Entities добавить класс UserInRole и заполнить его в соответствии со схемой базы данных. В папку Mapping добавить файл маппинга для класса UserInRole и реализовать его по образу и подобию StudentGroup.

**Comment by WonderfulFalcon** [comment]
Реализация этой таблицы в виде сущности не нужна.
